# Generated by Django 4.2 on 2025-06-21 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='securityevent',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Evento de Seguridad', 'verbose_name_plural': 'Eventos de Seguridad'},
        ),
        migrations.AddField(
            model_name='securityevent',
            name='lated_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
