# Generated by Django 4.2 on 2025-07-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_alter_securityevent_options_securityevent_lated_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizedperson',
            name='encoding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
