# Generated by Django 4.2 on 2025-07-10 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0003_authorizedperson_encoding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='securityevent',
            old_name='lated_user',
            new_name='related_user',
        ),
    ]
