# Generated by Django 4.2.30 on 2026-05-08 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0004_rename_lated_user_securityevent_related_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityevent',
            name='event_type',
            field=models.CharField(choices=[('face_recognized', 'Rostro reconocido'), ('face_unknown', 'Rostro desconocido'), ('dangerous_object', 'Objeto peligroso detectado'), ('ppe_missing', 'Falta de EPP'), ('ppe_incorrect', 'Uso incorrecto de EPP'), ('camera_error', 'Error de cámara')], max_length=50),
        ),
    ]
