# Generated by Django 4.2.30 on 2026-05-26 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0004_rename_lated_user_securityevent_related_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityevent',
            name='image_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
