# Generated by Django 4.2.30 on 2026-05-30 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('camera', '0006_camera_securityevent_camera'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorizedperson',
            options={'ordering': ['nombres', 'apellidos'], 'verbose_name': 'Persona autorizada', 'verbose_name_plural': 'Personas autorizadas'},
        ),
        migrations.RemoveField(
            model_name='authorizedperson',
            name='encoding',
        ),
        migrations.RemoveField(
            model_name='authorizedperson',
            name='user',
        ),
        migrations.AddField(
            model_name='authorizedperson',
            name='apellidos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='authorizedperson',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='authorizedperson',
            name='celular',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='authorizedperson',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='authorizedperson',
            name='face_image_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='authorizedperson',
            name='nombres',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='authorizedperson',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_people_registered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='authorized_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to='camera.authorizedperson'),
        ),
    ]
