# Generated by Django 4.2.30 on 2026-05-30 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0005_alter_securityevent_event_type'),
        ('camera', '0007_alter_authorizedperson_options_and_more'),
    ]

    operations = [
    ]
