# Generated by Django 4.2 on 2025-07-09 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('camara', models.CharField(max_length=100)),
                ('persona_detectada', models.CharField(blank=True, max_length=100, null=True)),
                ('epp_correcto', models.BooleanField(default=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
